In [1]:
import numpy as np
import pandas as pd

In [2]:
# .concat(['리스트로, 붙이고자하는, 데이터 프레임, 작성'])
# 세로로 이어붙이기

df_shot1 = pd.read_csv('data/13_diecasting_shot_1.csv')
df_shot2 = pd.read_csv('data/13_diecasting_shot_2.csv')

df_stacked = pd.concat([df_shot1, df_shot2]) # 1아레에 2가 붙음
print(df_stacked.shape)

(200, 8)

In [3]:
print(df_stacked.index[-3:].tolist()) 
# 200행짜리 데이터프레임에서 마지막 3개의 인덱스는 197,198,199여야 하는데
# concat으로 이어붙인 경우에는
# 이어붙이기 전에 자동을 부여된 인덱스가 그대로 유지됨
# 즉 0~99가 2개씩 존재하는거임

[97, 98, 99]

In [4]:
print(df_stacked.reset_index(drop=True))

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [5]:
df_shot = pd.read_csv("data/13_diecasting_shot.csv")
df_master = pd.read_csv('data/13_diecasting_master.csv')

In [6]:
df_new = pd.concat([df_shot, df_master],ignore_index=True)

In [7]:
print(df_new)
# 두 데이터셋의 모든 열이 추가되고,
# 값이 없는 빈칸으로 열에 값이 들어가며,
# 아래에 concat의 두 번째

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급   라인    도입연도  \
0    1.0  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품  NaN     NaN
1    2.0  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품  NaN     NaN
2    3.0  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품  NaN     NaN
3    4.0  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품  NaN     NaN
4    5.0  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품  NaN     NaN
..   ...       ...    ...     ...    ...    ...    ...  ...  ...     ...
200  NaN  DIE-A-01    NaN     NaN    NaN    NaN    NaN  NaN    A  2018.0
201  NaN  DIE-A-02    NaN     NaN    NaN    NaN    NaN  NaN    A  2019.0
202  NaN  DIE-B-01    NaN     NaN    NaN    NaN    NaN  NaN    B  2020.0
203  NaN  DIE-B-02    NaN     NaN    NaN    NaN    NaN  NaN    B  2021.0
204  NaN  DIE-D-01    NaN     NaN    NaN    NaN    NaN  NaN    D  2024.0

     정격형체력  담당반
0      NaN  NaN
1      NaN  NaN
2      NaN  NaN
3      NaN  NaN
4      NaN  NaN
..     ...  ...
200  280.0   1반
201  280.0   1반
202  320.0   2반
203  320.0   2반
204  350.0   3반

[205 rows x 12 columns]

In [8]:
print(df_new.columns)

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급', '라인',
       '도입연도', '정격형체력', '담당반'],
      dtype='object')

In [11]:
df_merged = df_shot.merge(df_master, on='설비ID', how='left')
line_ok = df_merged[df_merged['라인'].notna()]
print(len(line_ok))

notok = line_ok[line_ok['품질등급'] != '양품']
print(len(notok))

final = notok.sort_values('비스킷두께', ascending=False)
print(final[['샷', '설비ID', '라인', '비스킷두께', '품질등급']].head(5).to_string(index=False))

185
34
  샷     설비ID 라인  비스킷두께 품질등급
198 DIE-A-01  A   27.0   불량
192 DIE-B-01  B   26.0   불량
 43 DIE-A-01  A   21.0   주의
197 DIE-A-01  A   20.0   불량
171 DIE-B-02  B   20.0   주의

In [13]:
df_cycle = pd.read_csv('data/14_hydraulic.csv')
df_qc = pd.read_csv('data/14_hydraulic_qc.csv')

print(df_cycle.dtypes.to_dict())

{'냉각기상태': dtype('O'), '운전부하': dtype('O'), '밸브상태': dtype('O'), '온도': dtype('float64'), '진동': dtype('float64'), '압력': dtype('float64'), '냉각효율': dtype('float64'), 'result': dtype('O')}

In [18]:
print(df_cycle['냉각기상태'].value_counts(normalize=True).round(2))

냉각기상태
고장    0.33
저하    0.33
정상    0.33
Name: proportion, dtype: float64

In [ ]:
# 자주 사용하느느 vlaue_counts
# sort = False -> 개수 순서(오름차순) 대신에 데이터 등장 순서로 반환을 해줌
# dropna = False -> 빈칸도 하나의 종류로 보고 갯수를 카운팅해서 반환 해줌(원래는 빈칸은 무시하고 나머지 갯수만 반환)

In [ ]:
print(df_cycle['운전부하'].value_counts())

운전부하
고부하    60
저부하    60
Name: count, dtype: int64

In [21]:
print(df_cycle['운전부하'].value_counts(sort = False))

운전부하
고부하    60
저부하    60
Name: count, dtype: int64

In [ ]:
print(df_cycle['운전부하'].value_counts(dropna = False)) # 지금은 결측이 없기에 안나옴. 데이터셋 수정해서보면 나옴

운전부하
고부하    60
저부하    60
Name: count, dtype: int64

In [ ]:
print(df_cycle.shape)
print('='*20)
print(df_cycle['밸브상태'].value_counts())
print(df_cycle['밸브상태'].value_counts(normalize=True).round(3))
print('='*20)
print(df_cycle['운전부하'].value_counts())
print(df_cycle['운전부하'].value_counts(normalize=True).round(3))

(120, 8)
====================
밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64
밸브상태
정상    0.508
지연    0.167
경미    0.167
심각    0.158
Name: proportion, dtype: float64
====================
운전부하
고부하    60
저부하    60
Name: count, dtype: int64
운전부하
고부하    0.5
저부하    0.5
Name: proportion, dtype: float64

In [ ]:
# 수치형 데이터
# pd.cut([데이터프레임], bins=[경계값], labels= [구간의 이름표, 항상 bins보다 하나 적음])

temps_band = pd.cut(df_cycle['온도'], bins=[0, 40, 50, 200], labels=['low', 'mid', 'high'])
# 경계에 걸치는 경계값은 무조건 왼쪽 구간으로 포함된다 ex -> 40 = low
print(temps_band.value_counts())

온도
low     41
mid     40
high    39
Name: count, dtype: int64

In [29]:
print('max:',df_cycle['진동'].max(),'min:', df_cycle['진동'].min())
vib_band = pd.cut(df_cycle['진동'], 
                  bins=[0, 0.6, 0.7, 10],
                  labels=['약함', '보통', '강함'])

print(vib_band.value_counts())

max: 0.779 min: 0.53
진동
보통    55
약함    48
강함    17
Name: count, dtype: int64

In [ ]:
# 데이터프레임.group('상태기준열')['계산하고자하는열'].원하는연산

In [32]:
print(df_cycle.groupby('냉각기상태')['온도'].mean().round(2))
print(df_cycle.groupby('냉각기상태')['온도'].max().round(2))
print("가장 뜨거운 상태와 가장 시원한 상태의 평균차이(도):", 54.67-35.89)

냉각기상태
고장    54.67
저하    45.46
정상    35.89
Name: 온도, dtype: float64
냉각기상태
고장    57.8
저하    51.2
정상    36.4
Name: 온도, dtype: float64
가장 뜨거운 상태와 가장 시원한 상태의 평균차이(도): 18.78

In [47]:
print(df_cycle['밸브상태'].value_counts())
df_cycle_notok = df_cycle[df_cycle['result']=='고장']
print(df_cycle_notok['밸브상태'].value_counts())
print((df_cycle_notok['밸브상태'].value_counts()/df_cycle['밸브상태'].value_counts()).round(3))
print('='*25)
print(df_cycle['운전부하'].value_counts())
df_cycle_notok = df_cycle[df_cycle['result']=='고장']
print(df_cycle_notok['운전부하'].value_counts())
print((df_cycle_notok['운전부하'].value_counts()/df_cycle['운전부하'].value_counts()).round(3))

밸브상태
정상    61
지연    20
경미    20
심각    19
Name: count, dtype: int64
밸브상태
경미    14
심각    14
지연    13
정상    12
Name: count, dtype: int64
밸브상태
경미    0.700
심각    0.737
정상    0.197
지연    0.650
Name: count, dtype: float64
=========================
운전부하
고부하    60
저부하    60
Name: count, dtype: int64
운전부하
고부하    35
저부하    18
Name: count, dtype: int64
운전부하
고부하    0.583
저부하    0.300
Name: count, dtype: float64

In [51]:
summary = df_cycle.groupby('냉각기상태').agg(
        평균온도 = ('온도', 'mean'),
        온도편차 = ('온도', 'std'),
        최저온도 = ('온도', 'min'),
        평균진동 = ('진동', 'mean')
        )

print(summary)

          평균온도      온도편차  최저온도      평균진동
냉각기상태
고장     54.6675  3.759595  35.6  0.688125
저하     45.4650  1.465422  44.0  0.610125
정상     35.8850  0.355578  35.3  0.548650

In [ ]:
print(df_qc['검사결과'].value_counts())
print(df_qc.groupby('검사결과')['온도'].agg(['mean', 'std', 'max']).round(3))
summary_qc = df_qc.groupby('검사결과').agg(
    평균온도 = ('온도', 'mean'),
    평균냉각효율 = ('냉각효율', 'mean'),
    측정수 = ('냉각효율', 'count')
).round(3)
print('='*40)
print(summary_qc)
#불합격 평균 온도 = 55.842, 평균냉각효율은 19.650. 합격에 비해 불합격은 평균온도가 합격보다 약 20높고 냉각효율은 약 27정도 낮다

검사결과
합격     188
불합격     12
Name: count, dtype: int64
        mean    std   max
검사결과
불합격   55.842  1.322  57.5
합격    35.911  0.968  44.7
========================================
        평균온도  평균냉각효율  측정수
검사결과
불합격   55.842  19.650   12
합격    35.911  46.876  188

In [ ]:
df_cycle_copy = df_cycle.copy()
df_cycle_copy['그룸평균'] = df_cycle_copy.groupby('냉각기상태')['온도'].transform('mean').round(2)
# df_cycle에 그룸평균 열이 없기때문에 새로 만들어짐
# transform('mean'): 그룹별 평균 연산
pd.pivot_table(df, index='밸브상태', columns='운전부하',
values='온도', aggfunc='mean').round(2)

In [ ]:
pd.pivot_table(df_cycle, 
    index='밸브상태', # 결과 테이블의 열
    columns='운전부하', # 결과 테이블의 행
    values='온도',  # 계산에 사용되는 데이터
    aggfunc='mean' # 찾으려는 값
    ).round(2)

운전부하    고부하    저부하
밸브상태
경미    42.20  47.52
심각    45.25  47.09
정상    39.34  49.40
지연    43.75  49.79

In [ ]:
df_cycle_copy = df_cycle.copy()
df_cycle_copy['그룹평균'] = df_cycle_copy.groupby('냉각기상태')['온도'].transform('mean').round(2)
df_cycle_copy['편차'] = (df_cycle_copy['온도'] - df_cycle_copy['그룹평균']).round(2)
print(df_cycle_copy.head(3))
idx = df_cycle_copy['편차'].abs().idxmax()
print(df_cycle_copy.loc[idx, '냉각기상태'], df_cycle_copy['편차'][idx])

pd.pivot_table(df_cycle_copy, index='밸브상태', columns='운전부하', values='온도').round(2)

  냉각기상태 운전부하 밸브상태    온도     진동      압력  냉각효율 result   그룹평균     편차
0    고장  고부하   정상  35.6  0.577  160.67  39.6     정상  54.67 -19.07
1    고장  저부하   정상  47.5  0.604  158.65  17.6     정상  54.67  -7.17
2    고장  저부하   정상  50.7  0.640  157.76  18.7     정상  54.67  -3.97
고장 -19.07

운전부하    고부하    저부하
밸브상태
경미    42.20  47.52
심각    45.25  47.09
정상    39.34  49.40
지연    43.75  49.79

: